version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: "TenGym.Rabbitmq-web"
    networks:
      - tengymservicesnet
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    user: "root"
# =============== Databases ===============
  sql-server-product-db:
    image: mcr.microsoft.com/mssql/server
    container_name: TenGymServices.Database.Products
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=YOUR_PASS
      - ACCEPT_EULA=Y
    networks:
      - tengymservicesnet
# =============== Microservices ===============
  tengymservicesapiproducts:
    image: ${DOCKER_REGITRY-}tengymservicesapiproducts
    build:
      context: .
      dockerfile: TenGymServices.Api.Products/Dockerfile
    ports:
      - 6001:6001
    container_name: "TenGymServices.Api.Products"
    networks:
      - tengymservicesnet
    depends_on:
      - sql-server-product-db
      - rabbitmq
networks:
  tengymservicesnet:
    external: true
volumes:
  rabbitmq-data:
  rabbitmq-log:
    